/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.mycompany.research.avro;

import org.apache.avro.specific.SpecificData;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public class ReviewMessage extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -883489963287657117L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ReviewMessage\",\"namespace\":\"com.mycompany.research.avro\",\"fields\":[{\"name\":\"REVIEW_ID\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"ARTICLE_ID\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"ARTICLE_TITLE\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"REVIEWER_ID\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"REVIEWER_FIRST_NAME\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"REVIEWER_LAST_NAME\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"INSTITUTE_ID\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"INSTITUTE_NAME\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"COMMENT\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"CREATED_AT\",\"type\":[\"null\",\"long\"],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ReviewMessage> ENCODER =
      new BinaryMessageEncoder<ReviewMessage>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ReviewMessage> DECODER =
      new BinaryMessageDecoder<ReviewMessage>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   */
  public static BinaryMessageDecoder<ReviewMessage> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   */
  public static BinaryMessageDecoder<ReviewMessage> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<ReviewMessage>(MODEL$, SCHEMA$, resolver);
  }

  /** Serializes this ReviewMessage to a ByteBuffer. */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /** Deserializes a ReviewMessage from a ByteBuffer. */
  public static ReviewMessage fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  @Deprecated public java.lang.Long REVIEW_ID;
  @Deprecated public java.lang.Long ARTICLE_ID;
  @Deprecated public java.lang.CharSequence ARTICLE_TITLE;
  @Deprecated public java.lang.Long REVIEWER_ID;
  @Deprecated public java.lang.CharSequence REVIEWER_FIRST_NAME;
  @Deprecated public java.lang.CharSequence REVIEWER_LAST_NAME;
  @Deprecated public java.lang.Long INSTITUTE_ID;
  @Deprecated public java.lang.CharSequence INSTITUTE_NAME;
  @Deprecated public java.lang.CharSequence COMMENT;
  @Deprecated public java.lang.Long CREATED_AT;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ReviewMessage() {}

  /**
   * All-args constructor.
   * @param REVIEW_ID The new value for REVIEW_ID
   * @param ARTICLE_ID The new value for ARTICLE_ID
   * @param ARTICLE_TITLE The new value for ARTICLE_TITLE
   * @param REVIEWER_ID The new value for REVIEWER_ID
   * @param REVIEWER_FIRST_NAME The new value for REVIEWER_FIRST_NAME
   * @param REVIEWER_LAST_NAME The new value for REVIEWER_LAST_NAME
   * @param INSTITUTE_ID The new value for INSTITUTE_ID
   * @param INSTITUTE_NAME The new value for INSTITUTE_NAME
   * @param COMMENT The new value for COMMENT
   * @param CREATED_AT The new value for CREATED_AT
   */
  public ReviewMessage(java.lang.Long REVIEW_ID, java.lang.Long ARTICLE_ID, java.lang.CharSequence ARTICLE_TITLE, java.lang.Long REVIEWER_ID, java.lang.CharSequence REVIEWER_FIRST_NAME, java.lang.CharSequence REVIEWER_LAST_NAME, java.lang.Long INSTITUTE_ID, java.lang.CharSequence INSTITUTE_NAME, java.lang.CharSequence COMMENT, java.lang.Long CREATED_AT) {
    this.REVIEW_ID = REVIEW_ID;
    this.ARTICLE_ID = ARTICLE_ID;
    this.ARTICLE_TITLE = ARTICLE_TITLE;
    this.REVIEWER_ID = REVIEWER_ID;
    this.REVIEWER_FIRST_NAME = REVIEWER_FIRST_NAME;
    this.REVIEWER_LAST_NAME = REVIEWER_LAST_NAME;
    this.INSTITUTE_ID = INSTITUTE_ID;
    this.INSTITUTE_NAME = INSTITUTE_NAME;
    this.COMMENT = COMMENT;
    this.CREATED_AT = CREATED_AT;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return REVIEW_ID;
    case 1: return ARTICLE_ID;
    case 2: return ARTICLE_TITLE;
    case 3: return REVIEWER_ID;
    case 4: return REVIEWER_FIRST_NAME;
    case 5: return REVIEWER_LAST_NAME;
    case 6: return INSTITUTE_ID;
    case 7: return INSTITUTE_NAME;
    case 8: return COMMENT;
    case 9: return CREATED_AT;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: REVIEW_ID = (java.lang.Long)value$; break;
    case 1: ARTICLE_ID = (java.lang.Long)value$; break;
    case 2: ARTICLE_TITLE = (java.lang.CharSequence)value$; break;
    case 3: REVIEWER_ID = (java.lang.Long)value$; break;
    case 4: REVIEWER_FIRST_NAME = (java.lang.CharSequence)value$; break;
    case 5: REVIEWER_LAST_NAME = (java.lang.CharSequence)value$; break;
    case 6: INSTITUTE_ID = (java.lang.Long)value$; break;
    case 7: INSTITUTE_NAME = (java.lang.CharSequence)value$; break;
    case 8: COMMENT = (java.lang.CharSequence)value$; break;
    case 9: CREATED_AT = (java.lang.Long)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'REVIEW_ID' field.
   * @return The value of the 'REVIEW_ID' field.
   */
  public java.lang.Long getREVIEWID() {
    return REVIEW_ID;
  }

  /**
   * Sets the value of the 'REVIEW_ID' field.
   * @param value the value to set.
   */
  public void setREVIEWID(java.lang.Long value) {
    this.REVIEW_ID = value;
  }

  /**
   * Gets the value of the 'ARTICLE_ID' field.
   * @return The value of the 'ARTICLE_ID' field.
   */
  public java.lang.Long getARTICLEID() {
    return ARTICLE_ID;
  }

  /**
   * Sets the value of the 'ARTICLE_ID' field.
   * @param value the value to set.
   */
  public void setARTICLEID(java.lang.Long value) {
    this.ARTICLE_ID = value;
  }

  /**
   * Gets the value of the 'ARTICLE_TITLE' field.
   * @return The value of the 'ARTICLE_TITLE' field.
   */
  public java.lang.CharSequence getARTICLETITLE() {
    return ARTICLE_TITLE;
  }

  /**
   * Sets the value of the 'ARTICLE_TITLE' field.
   * @param value the value to set.
   */
  public void setARTICLETITLE(java.lang.CharSequence value) {
    this.ARTICLE_TITLE = value;
  }

  /**
   * Gets the value of the 'REVIEWER_ID' field.
   * @return The value of the 'REVIEWER_ID' field.
   */
  public java.lang.Long getREVIEWERID() {
    return REVIEWER_ID;
  }

  /**
   * Sets the value of the 'REVIEWER_ID' field.
   * @param value the value to set.
   */
  public void setREVIEWERID(java.lang.Long value) {
    this.REVIEWER_ID = value;
  }

  /**
   * Gets the value of the 'REVIEWER_FIRST_NAME' field.
   * @return The value of the 'REVIEWER_FIRST_NAME' field.
   */
  public java.lang.CharSequence getREVIEWERFIRSTNAME() {
    return REVIEWER_FIRST_NAME;
  }

  /**
   * Sets the value of the 'REVIEWER_FIRST_NAME' field.
   * @param value the value to set.
   */
  public void setREVIEWERFIRSTNAME(java.lang.CharSequence value) {
    this.REVIEWER_FIRST_NAME = value;
  }

  /**
   * Gets the value of the 'REVIEWER_LAST_NAME' field.
   * @return The value of the 'REVIEWER_LAST_NAME' field.
   */
  public java.lang.CharSequence getREVIEWERLASTNAME() {
    return REVIEWER_LAST_NAME;
  }

  /**
   * Sets the value of the 'REVIEWER_LAST_NAME' field.
   * @param value the value to set.
   */
  public void setREVIEWERLASTNAME(java.lang.CharSequence value) {
    this.REVIEWER_LAST_NAME = value;
  }

  /**
   * Gets the value of the 'INSTITUTE_ID' field.
   * @return The value of the 'INSTITUTE_ID' field.
   */
  public java.lang.Long getINSTITUTEID() {
    return INSTITUTE_ID;
  }

  /**
   * Sets the value of the 'INSTITUTE_ID' field.
   * @param value the value to set.
   */
  public void setINSTITUTEID(java.lang.Long value) {
    this.INSTITUTE_ID = value;
  }

  /**
   * Gets the value of the 'INSTITUTE_NAME' field.
   * @return The value of the 'INSTITUTE_NAME' field.
   */
  public java.lang.CharSequence getINSTITUTENAME() {
    return INSTITUTE_NAME;
  }

  /**
   * Sets the value of the 'INSTITUTE_NAME' field.
   * @param value the value to set.
   */
  public void setINSTITUTENAME(java.lang.CharSequence value) {
    this.INSTITUTE_NAME = value;
  }

  /**
   * Gets the value of the 'COMMENT' field.
   * @return The value of the 'COMMENT' field.
   */
  public java.lang.CharSequence getCOMMENT() {
    return COMMENT;
  }

  /**
   * Sets the value of the 'COMMENT' field.
   * @param value the value to set.
   */
  public void setCOMMENT(java.lang.CharSequence value) {
    this.COMMENT = value;
  }

  /**
   * Gets the value of the 'CREATED_AT' field.
   * @return The value of the 'CREATED_AT' field.
   */
  public java.lang.Long getCREATEDAT() {
    return CREATED_AT;
  }

  /**
   * Sets the value of the 'CREATED_AT' field.
   * @param value the value to set.
   */
  public void setCREATEDAT(java.lang.Long value) {
    this.CREATED_AT = value;
  }

  /**
   * Creates a new ReviewMessage RecordBuilder.
   * @return A new ReviewMessage RecordBuilder
   */
  public static com.mycompany.research.avro.ReviewMessage.Builder newBuilder() {
    return new com.mycompany.research.avro.ReviewMessage.Builder();
  }

  /**
   * Creates a new ReviewMessage RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ReviewMessage RecordBuilder
   */
  public static com.mycompany.research.avro.ReviewMessage.Builder newBuilder(com.mycompany.research.avro.ReviewMessage.Builder other) {
    return new com.mycompany.research.avro.ReviewMessage.Builder(other);
  }

  /**
   * Creates a new ReviewMessage RecordBuilder by copying an existing ReviewMessage instance.
   * @param other The existing instance to copy.
   * @return A new ReviewMessage RecordBuilder
   */
  public static com.mycompany.research.avro.ReviewMessage.Builder newBuilder(com.mycompany.research.avro.ReviewMessage other) {
    return new com.mycompany.research.avro.ReviewMessage.Builder(other);
  }

  /**
   * RecordBuilder for ReviewMessage instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ReviewMessage>
    implements org.apache.avro.data.RecordBuilder<ReviewMessage> {

    private java.lang.Long REVIEW_ID;
    private java.lang.Long ARTICLE_ID;
    private java.lang.CharSequence ARTICLE_TITLE;
    private java.lang.Long REVIEWER_ID;
    private java.lang.CharSequence REVIEWER_FIRST_NAME;
    private java.lang.CharSequence REVIEWER_LAST_NAME;
    private java.lang.Long INSTITUTE_ID;
    private java.lang.CharSequence INSTITUTE_NAME;
    private java.lang.CharSequence COMMENT;
    private java.lang.Long CREATED_AT;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.mycompany.research.avro.ReviewMessage.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.REVIEW_ID)) {
        this.REVIEW_ID = data().deepCopy(fields()[0].schema(), other.REVIEW_ID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ARTICLE_ID)) {
        this.ARTICLE_ID = data().deepCopy(fields()[1].schema(), other.ARTICLE_ID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ARTICLE_TITLE)) {
        this.ARTICLE_TITLE = data().deepCopy(fields()[2].schema(), other.ARTICLE_TITLE);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.REVIEWER_ID)) {
        this.REVIEWER_ID = data().deepCopy(fields()[3].schema(), other.REVIEWER_ID);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.REVIEWER_FIRST_NAME)) {
        this.REVIEWER_FIRST_NAME = data().deepCopy(fields()[4].schema(), other.REVIEWER_FIRST_NAME);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.REVIEWER_LAST_NAME)) {
        this.REVIEWER_LAST_NAME = data().deepCopy(fields()[5].schema(), other.REVIEWER_LAST_NAME);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.INSTITUTE_ID)) {
        this.INSTITUTE_ID = data().deepCopy(fields()[6].schema(), other.INSTITUTE_ID);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.INSTITUTE_NAME)) {
        this.INSTITUTE_NAME = data().deepCopy(fields()[7].schema(), other.INSTITUTE_NAME);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.COMMENT)) {
        this.COMMENT = data().deepCopy(fields()[8].schema(), other.COMMENT);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.CREATED_AT)) {
        this.CREATED_AT = data().deepCopy(fields()[9].schema(), other.CREATED_AT);
        fieldSetFlags()[9] = true;
      }
    }

    /**
     * Creates a Builder by copying an existing ReviewMessage instance
     * @param other The existing instance to copy.
     */
    private Builder(com.mycompany.research.avro.ReviewMessage other) {
            super(SCHEMA$);
      if (isValidValue(fields()[0], other.REVIEW_ID)) {
        this.REVIEW_ID = data().deepCopy(fields()[0].schema(), other.REVIEW_ID);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.ARTICLE_ID)) {
        this.ARTICLE_ID = data().deepCopy(fields()[1].schema(), other.ARTICLE_ID);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.ARTICLE_TITLE)) {
        this.ARTICLE_TITLE = data().deepCopy(fields()[2].schema(), other.ARTICLE_TITLE);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.REVIEWER_ID)) {
        this.REVIEWER_ID = data().deepCopy(fields()[3].schema(), other.REVIEWER_ID);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.REVIEWER_FIRST_NAME)) {
        this.REVIEWER_FIRST_NAME = data().deepCopy(fields()[4].schema(), other.REVIEWER_FIRST_NAME);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.REVIEWER_LAST_NAME)) {
        this.REVIEWER_LAST_NAME = data().deepCopy(fields()[5].schema(), other.REVIEWER_LAST_NAME);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.INSTITUTE_ID)) {
        this.INSTITUTE_ID = data().deepCopy(fields()[6].schema(), other.INSTITUTE_ID);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.INSTITUTE_NAME)) {
        this.INSTITUTE_NAME = data().deepCopy(fields()[7].schema(), other.INSTITUTE_NAME);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.COMMENT)) {
        this.COMMENT = data().deepCopy(fields()[8].schema(), other.COMMENT);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.CREATED_AT)) {
        this.CREATED_AT = data().deepCopy(fields()[9].schema(), other.CREATED_AT);
        fieldSetFlags()[9] = true;
      }
    }

    /**
      * Gets the value of the 'REVIEW_ID' field.
      * @return The value.
      */
    public java.lang.Long getREVIEWID() {
      return REVIEW_ID;
    }

    /**
      * Sets the value of the 'REVIEW_ID' field.
      * @param value The value of 'REVIEW_ID'.
      * @return This builder.
      */
    public com.mycompany.research.avro.ReviewMessage.Builder setREVIEWID(java.lang.Long value) {
      validate(fields()[0], value);
      this.REVIEW_ID = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'REVIEW_ID' field has been set.
      * @return True if the 'REVIEW_ID' field has been set, false otherwise.
      */
    public boolean hasREVIEWID() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'REVIEW_ID' field.
      * @return This builder.
      */
    public com.mycompany.research.avro.ReviewMessage.Builder clearREVIEWID() {
      REVIEW_ID = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'ARTICLE_ID' field.
      * @return The value.
      */
    public java.lang.Long getARTICLEID() {
      return ARTICLE_ID;
    }

    /**
      * Sets the value of the 'ARTICLE_ID' field.
      * @param value The value of 'ARTICLE_ID'.
      * @return This builder.
      */
    public com.mycompany.research.avro.ReviewMessage.Builder setARTICLEID(java.lang.Long value) {
      validate(fields()[1], value);
      this.ARTICLE_ID = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'ARTICLE_ID' field has been set.
      * @return True if the 'ARTICLE_ID' field has been set, false otherwise.
      */
    public boolean hasARTICLEID() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'ARTICLE_ID' field.
      * @return This builder.
      */
    public com.mycompany.research.avro.ReviewMessage.Builder clearARTICLEID() {
      ARTICLE_ID = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'ARTICLE_TITLE' field.
      * @return The value.
      */
    public java.lang.CharSequence getARTICLETITLE() {
      return ARTICLE_TITLE;
    }

    /**
      * Sets the value of the 'ARTICLE_TITLE' field.
      * @param value The value of 'ARTICLE_TITLE'.
      * @return This builder.
      */
    public com.mycompany.research.avro.ReviewMessage.Builder setARTICLETITLE(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.ARTICLE_TITLE = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'ARTICLE_TITLE' field has been set.
      * @return True if the 'ARTICLE_TITLE' field has been set, false otherwise.
      */
    public boolean hasARTICLETITLE() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'ARTICLE_TITLE' field.
      * @return This builder.
      */
    public com.mycompany.research.avro.ReviewMessage.Builder clearARTICLETITLE() {
      ARTICLE_TITLE = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'REVIEWER_ID' field.
      * @return The value.
      */
    public java.lang.Long getREVIEWERID() {
      return REVIEWER_ID;
    }

    /**
      * Sets the value of the 'REVIEWER_ID' field.
      * @param value The value of 'REVIEWER_ID'.
      * @return This builder.
      */
    public com.mycompany.research.avro.ReviewMessage.Builder setREVIEWERID(java.lang.Long value) {
      validate(fields()[3], value);
      this.REVIEWER_ID = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'REVIEWER_ID' field has been set.
      * @return True if the 'REVIEWER_ID' field has been set, false otherwise.
      */
    public boolean hasREVIEWERID() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'REVIEWER_ID' field.
      * @return This builder.
      */
    public com.mycompany.research.avro.ReviewMessage.Builder clearREVIEWERID() {
      REVIEWER_ID = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'REVIEWER_FIRST_NAME' field.
      * @return The value.
      */
    public java.lang.CharSequence getREVIEWERFIRSTNAME() {
      return REVIEWER_FIRST_NAME;
    }

    /**
      * Sets the value of the 'REVIEWER_FIRST_NAME' field.
      * @param value The value of 'REVIEWER_FIRST_NAME'.
      * @return This builder.
      */
    public com.mycompany.research.avro.ReviewMessage.Builder setREVIEWERFIRSTNAME(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.REVIEWER_FIRST_NAME = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'REVIEWER_FIRST_NAME' field has been set.
      * @return True if the 'REVIEWER_FIRST_NAME' field has been set, false otherwise.
      */
    public boolean hasREVIEWERFIRSTNAME() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'REVIEWER_FIRST_NAME' field.
      * @return This builder.
      */
    public com.mycompany.research.avro.ReviewMessage.Builder clearREVIEWERFIRSTNAME() {
      REVIEWER_FIRST_NAME = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'REVIEWER_LAST_NAME' field.
      * @return The value.
      */
    public java.lang.CharSequence getREVIEWERLASTNAME() {
      return REVIEWER_LAST_NAME;
    }

    /**
      * Sets the value of the 'REVIEWER_LAST_NAME' field.
      * @param value The value of 'REVIEWER_LAST_NAME'.
      * @return This builder.
      */
    public com.mycompany.research.avro.ReviewMessage.Builder setREVIEWERLASTNAME(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.REVIEWER_LAST_NAME = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'REVIEWER_LAST_NAME' field has been set.
      * @return True if the 'REVIEWER_LAST_NAME' field has been set, false otherwise.
      */
    public boolean hasREVIEWERLASTNAME() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'REVIEWER_LAST_NAME' field.
      * @return This builder.
      */
    public com.mycompany.research.avro.ReviewMessage.Builder clearREVIEWERLASTNAME() {
      REVIEWER_LAST_NAME = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'INSTITUTE_ID' field.
      * @return The value.
      */
    public java.lang.Long getINSTITUTEID() {
      return INSTITUTE_ID;
    }

    /**
      * Sets the value of the 'INSTITUTE_ID' field.
      * @param value The value of 'INSTITUTE_ID'.
      * @return This builder.
      */
    public com.mycompany.research.avro.ReviewMessage.Builder setINSTITUTEID(java.lang.Long value) {
      validate(fields()[6], value);
      this.INSTITUTE_ID = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'INSTITUTE_ID' field has been set.
      * @return True if the 'INSTITUTE_ID' field has been set, false otherwise.
      */
    public boolean hasINSTITUTEID() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'INSTITUTE_ID' field.
      * @return This builder.
      */
    public com.mycompany.research.avro.ReviewMessage.Builder clearINSTITUTEID() {
      INSTITUTE_ID = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'INSTITUTE_NAME' field.
      * @return The value.
      */
    public java.lang.CharSequence getINSTITUTENAME() {
      return INSTITUTE_NAME;
    }

    /**
      * Sets the value of the 'INSTITUTE_NAME' field.
      * @param value The value of 'INSTITUTE_NAME'.
      * @return This builder.
      */
    public com.mycompany.research.avro.ReviewMessage.Builder setINSTITUTENAME(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.INSTITUTE_NAME = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'INSTITUTE_NAME' field has been set.
      * @return True if the 'INSTITUTE_NAME' field has been set, false otherwise.
      */
    public boolean hasINSTITUTENAME() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'INSTITUTE_NAME' field.
      * @return This builder.
      */
    public com.mycompany.research.avro.ReviewMessage.Builder clearINSTITUTENAME() {
      INSTITUTE_NAME = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'COMMENT' field.
      * @return The value.
      */
    public java.lang.CharSequence getCOMMENT() {
      return COMMENT;
    }

    /**
      * Sets the value of the 'COMMENT' field.
      * @param value The value of 'COMMENT'.
      * @return This builder.
      */
    public com.mycompany.research.avro.ReviewMessage.Builder setCOMMENT(java.lang.CharSequence value) {
      validate(fields()[8], value);
      this.COMMENT = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'COMMENT' field has been set.
      * @return True if the 'COMMENT' field has been set, false otherwise.
      */
    public boolean hasCOMMENT() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'COMMENT' field.
      * @return This builder.
      */
    public com.mycompany.research.avro.ReviewMessage.Builder clearCOMMENT() {
      COMMENT = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'CREATED_AT' field.
      * @return The value.
      */
    public java.lang.Long getCREATEDAT() {
      return CREATED_AT;
    }

    /**
      * Sets the value of the 'CREATED_AT' field.
      * @param value The value of 'CREATED_AT'.
      * @return This builder.
      */
    public com.mycompany.research.avro.ReviewMessage.Builder setCREATEDAT(java.lang.Long value) {
      validate(fields()[9], value);
      this.CREATED_AT = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'CREATED_AT' field has been set.
      * @return True if the 'CREATED_AT' field has been set, false otherwise.
      */
    public boolean hasCREATEDAT() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'CREATED_AT' field.
      * @return This builder.
      */
    public com.mycompany.research.avro.ReviewMessage.Builder clearCREATEDAT() {
      CREATED_AT = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ReviewMessage build() {
      try {
        ReviewMessage record = new ReviewMessage();
        record.REVIEW_ID = fieldSetFlags()[0] ? this.REVIEW_ID : (java.lang.Long) defaultValue(fields()[0]);
        record.ARTICLE_ID = fieldSetFlags()[1] ? this.ARTICLE_ID : (java.lang.Long) defaultValue(fields()[1]);
        record.ARTICLE_TITLE = fieldSetFlags()[2] ? this.ARTICLE_TITLE : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.REVIEWER_ID = fieldSetFlags()[3] ? this.REVIEWER_ID : (java.lang.Long) defaultValue(fields()[3]);
        record.REVIEWER_FIRST_NAME = fieldSetFlags()[4] ? this.REVIEWER_FIRST_NAME : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.REVIEWER_LAST_NAME = fieldSetFlags()[5] ? this.REVIEWER_LAST_NAME : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.INSTITUTE_ID = fieldSetFlags()[6] ? this.INSTITUTE_ID : (java.lang.Long) defaultValue(fields()[6]);
        record.INSTITUTE_NAME = fieldSetFlags()[7] ? this.INSTITUTE_NAME : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.COMMENT = fieldSetFlags()[8] ? this.COMMENT : (java.lang.CharSequence) defaultValue(fields()[8]);
        record.CREATED_AT = fieldSetFlags()[9] ? this.CREATED_AT : (java.lang.Long) defaultValue(fields()[9]);
        return record;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ReviewMessage>
    WRITER$ = (org.apache.avro.io.DatumWriter<ReviewMessage>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ReviewMessage>
    READER$ = (org.apache.avro.io.DatumReader<ReviewMessage>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}
